services:
  flareddns:
    image: sashatech/flareddns:latest
    platform: linux/amd64
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
